[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
VOFTools = "f4b4545c-59ad-49ee-afe8-a74df8bf51d2"

[sources]
VOFTools = {path = "/home/libat/github/PenguinxCutCell/VOFTools.jl"}

[compat]
Documenter = "1"
